PREFIX mail: <https://mail.described.at/>
PREFIX schema: <http://schema.org/>

SELECT ?thread (COUNT(DISTINCT ?msg) AS ?msgCount) (COUNT(DISTINCT ?sender) AS ?participants) (SAMPLE(?subject) AS ?sampleSubject) WHERE {
  ?msg mail:thread ?thread ;
       mail:from ?sender .
  OPTIONAL { ?msg mail:subject ?subject }
}
GROUP BY ?thread
HAVING (?participants > 2)
ORDER BY DESC(?participants)
LIMIT 20
