PREFIX mail: <https://mail.described.at/>
PREFIX schema: <http://schema.org/>

SELECT ?email (SAMPLE(?name) AS ?displayName) (COUNT(?msg) AS ?count) WHERE {
  ?msg mail:from ?sender .
  ?sender schema:email ?email .
  OPTIONAL { ?sender schema:name ?name }
}
GROUP BY ?email
ORDER BY DESC(?count)
LIMIT 10